_target_: models.tokenizer.Tokenizer

vocab_size: 512
embed_dim: 512
encoder:
  _target_: models.tokenizer.Encoder
  config:
    _target_: models.tokenizer.EncoderDecoderConfig
    resolution: 64
    in_channels: 3
    z_channels: 512
    ch: 64
    ch_mult: [1, 1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: models.tokenizer.Decoder
  config: ${..encoder.config}